WardrobeApp/Controllers/OutfitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WardrobeApp.Content;

namespace WardrobeApp.Controllers
{
    public class OutfitsController : Controller
    {
        private DressItDBEntities db = new DressItDBEntities();

        // GET: Outfits
        public ActionResult Index()
        {
            var outfits = db.Outfits.Include(o => o.Top).Include(o => o.Bottom).Include(o => o.Shoes);
            return View(outfits.ToList());
        }

        // GET: Outfits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Outfit outfit = db.Outfits.Find(id);
            if (outfit == null)
            {
                return HttpNotFound();
            }
            return View(outfit);
        }

        // GET: Outfits/Create
        public ActionResult Create()
        {
            var possibleTops = from item in db.WardrobeItems
                                   //where item.Type.TypeName == "Top"
                               where item.TypeID == 1
                               select item;

            var possibleBottoms = from item in db.WardrobeItems
                                      //where item.Type.TypeName == "Bottom"
                                  where item.TypeID == 2
                                  select item;

            var possibleShoes = from item in db.WardrobeItems
                                    //where item.Type.TypeName == "Shoes"
                                where item.TypeID == 3
                                select item;

            var possibleAccessories = from item in db.WardrobeItems
                                          //where item.Type.TypeName == "Accessories"
                                      where item.TypeID == 4
                                      select item;


            ViewBag.TopID = new SelectList(possibleTops, "WardrobeItemID", "Name");
            ViewBag.BottomId = new SelectList(possibleBottoms, "WardrobeItemID", "Name");
            ViewBag.ShoeID = new SelectList(possibleShoes, "WardrobeItemID", "Name");
            ViewBag.AccessoryID = new MultiSelectList(possibleAccessories, "WardrobeItemID", "Name");
            return View();
        }

        // POST: Outfits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OutfitID,TopID,BottomId,ShoeID")] Outfit outfit, int[] AccessoryID)
        {

            if (ModelState.IsValid)
            {
                foreach(var item in AccessoryID)
                {
                    outfit.Accessories.Add(db.WardrobeItems.Find(item));
                }
                db.Outfits.Add(outfit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TopID = new SelectList(db.WardrobeItems, "WardrobeItemID", "Name", outfit.TopID);
            ViewBag.BottomId = new SelectList(db.WardrobeItems, "WardrobeItemID", "Name", outfit.BottomId);
            ViewBag.ShoeID = new SelectList(db.WardrobeItems, "WardrobeItemID", "Name", outfit.ShoeID);
            return View(outfit);
        }

        // GET: Outfits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Outfit outfit = db.Outfits.Find(id);
            if (outfit == null)
            {
                return HttpNotFound();
            }
            ViewBag.TopID = new SelectList(db.WardrobeItems, "WardrobeItemID", "Name", outfit.TopID);
            ViewBag.BottomId = new SelectList(db.WardrobeItems, "WardrobeItemID", "Name", outfit.BottomId);
            ViewBag.ShoeID = new SelectList(db.WardrobeItems, "WardrobeItemID", "Name", outfit.ShoeID);
            return View(outfit);
        }

        // POST: Outfits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OutfitID,TopID,BottomId,ShoeID")] Outfit outfit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(outfit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TopID = new SelectList(db.WardrobeItems, "WardrobeItemID", "Name", outfit.TopID);
            ViewBag.BottomId = new SelectList(db.WardrobeItems, "WardrobeItemID", "Name", outfit.BottomId);
            ViewBag.ShoeID = new SelectList(db.WardrobeItems, "WardrobeItemID", "Name", outfit.ShoeID);
            return View(outfit);
        }

        // GET: Outfits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Outfit outfit = db.Outfits.Find(id);
            if (outfit == null)
            {
                return HttpNotFound();
            }
            return View(outfit);
        }

        // POST: Outfits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Outfit outfit = db.Outfits.Find(id);
            outfit.Accessories.Clear();
            db.Outfits.Remove(outfit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WardrobeApp/Controllers/WardrobeItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WardrobeApp.Content;

namespace WardrobeApp.Controllers
{
    public class WardrobeItemsController : Controller
    {
        private DressItDBEntities db = new DressItDBEntities();

        // GET: WardrobeItems
        public ActionResult Index()
        {
            var wardrobeItems = db.WardrobeItems.Include(w => w.Type);
            return View(wardrobeItems.ToList());
        }

        // GET: WardrobeItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WardrobeItem wardrobeItem = db.WardrobeItems.Find(id);
            if (wardrobeItem == null)
            {
                return HttpNotFound();
            }
            return View(wardrobeItem);
        }

        // GET: WardrobeItems/Create
        public ActionResult Create()
        {
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "TypeName");
            return View();
        }

        // POST: WardrobeItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "WardrobeItemID,TypeID,Name,Photo")] WardrobeItem wardrobeItem)
        {
            if (ModelState.IsValid)
            {
                db.WardrobeItems.Add(wardrobeItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "TypeName", wardrobeItem.TypeID);
            return View(wardrobeItem);
        }

        // GET: WardrobeItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WardrobeItem wardrobeItem = db.WardrobeItems.Find(id);
            if (wardrobeItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "TypeName", wardrobeItem.TypeID);
            return View(wardrobeItem);
        }

        // POST: WardrobeItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WardrobeItemID,TypeID,Name,Photo")] WardrobeItem wardrobeItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wardrobeItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "TypeName", wardrobeItem.TypeID);
            return View(wardrobeItem);
        }

        // GET: WardrobeItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WardrobeItem wardrobeItem = db.WardrobeItems.Find(id);
            if (wardrobeItem == null)
            {
                return HttpNotFound();
            }
            return View(wardrobeItem);
        }

        // POST: WardrobeItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WardrobeItem wardrobeItem = db.WardrobeItems.Find(id);
            db.WardrobeItems.Remove(wardrobeItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WardrobeApp/Views/Outfits/Create.cshtml
@model WardrobeApp.Content.Outfit

@{
    ViewBag.Title = "Create";
}

@*<h2>Create</h2>*@


        <div class="row">
            <a href="#menu.toggledR" class="btn btn-default" id="menu-toggleR">Toggle SlideShow</a>
            <hr />
        </div>



@*<div id="sidebar-wrapperR">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <a href="">SlideShow</a>
            </li> <!--end sidebar-brand-->

        </ul> <!--end sidebar-nav -->
    </div> <!--end sidebar-wrapper-->*@




<!--Side Bar/Slideshow-->
@*<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a href="">My Closet</a>
        </li> <!--end sidebar-brand-->
        <li class="dropdown">
            <a href="" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Closet <span class="caret"></span> </a>
            <ul class="dropdown-menu">
                <li><a href="@Url.Action("Create","WardrobeItems")"> <i class="fa fa-angle-double-right"></i>Add to closet</a></li>
                <li><a href="@Url.Action("Index","WardrobeItems")"> <i class="fa fa-angle-double-right"></i>Enter closet</a></li>
            </ul>
        </li>

        <!--Outfit submenu-->
        <li class="dropdown">
            <a href="" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Outfits <span class="caret"></span> </a>
            <ul class="dropdown-menu">
                <li><a href="@Url.Action("Create","Outfits")"> <i class="fa fa-angle-double-right"></i>New Outfit</a></li>
                <li><a href="@Url.Action("Index","Outfits")"> <i class="fa fa-angle-double-right"></i>Saved Outfits</a></li>
            </ul>
        </li>


    </ul> <!--end sidebar-nav -->
</div> <!--end sidebar-wrapper-->*@

<!--Outfit -->



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Outfit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TopID, "TopID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TopID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TopID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BottomId, "BottomId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BottomId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BottomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShoeID, "ShoeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShoeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShoeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Accessories, "Accessories", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("AccessoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Accessories, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
    <!-- Menu Toggle Script -->
@*<script>
        $("#menu-toggleR").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
</script>*@

WardrobeApp/Views/Outfits/Delete.cshtml
@model WardrobeApp.Content.Outfit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Outfit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Top.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Top.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bottom.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bottom.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shoes.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shoes.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WardrobeApp/Views/Outfits/Details.cshtml
@model WardrobeApp.Content.Outfit

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Outfit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Top.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Top.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bottom.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bottom.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shoes.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shoes.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OutfitID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WardrobeApp/Views/Outfits/Edit.cshtml
@model WardrobeApp.Content.Outfit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Outfit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OutfitID)

        <div class="form-group">
            @Html.LabelFor(model => model.TopID, "TopID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TopID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TopID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BottomId, "BottomId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BottomId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BottomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShoeID, "ShoeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShoeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShoeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WardrobeApp/Views/Outfits/Index.cshtml
@model IEnumerable<WardrobeApp.Content.Outfit>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Top
        </th>
        <th>
            Bottom
        </th>
        <th>
            Shoes
        </th>
        <th>
            Accessories
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @*@Html.DisplayFor(modelItem => item.Top.Name)*@
            @item.Top.Name
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bottom.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Shoes.Name)
        </td>
        <td>
            @foreach (var accessory in item.Accessories)
            {
                @Html.DisplayFor(modelItem => accessory.Name);
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.OutfitID }) |
            @Html.ActionLink("Details", "Details", new { id=item.OutfitID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.OutfitID })
        </td>
    </tr>
}

</table>